config/routes.rb
Projekt::Application.routes.draw do
  devise_for :users
  
  mount Resque::Server, :at => "/resque"
   

  
  
    
    
    match '/search' => 'application#search', :as => :search
  
  match '/autoCompl' => 'application#autoCompl', :as => :autoCompl
  
  scope "(:locale)", :locale => /de|en/ do
    root :to => 'welcome#index', :as => :welcome
    
    resources :user, :except => [:show, :destroy]
    match '/user/most_active' => 'user#most_active', :as => :most_active_user
    match 'user/reset_password' => 'user#reset_password', :as => :reset_password
    match '/user/setAdmin/:id' => 'user#set_as_admin', :as => :set_as_admin, :via => :get
    match '/user/setUser/:id' => 'user#set_as_user', :as => :set_as_user, :via => :get
    match '/user/:id' => 'user#show', :as => :user, :via => :get
    match '/user/:id' => 'user#destroy', :as => :delete_user, :via => :delete
   
    
    resources :devise
    match 'compact_disk/mbrainz/' => 'compact_disk#mbrainz', :as => :mbrainz, :via => :get
    
    resources :compact_disk, :except => [:show, :destroy]
    match '/comapct_disk/delete_demo_songs:id' => 'compact_disk#delete_demo_songs', :as => :delete_demo_songs, :via => :delete
    match '/compact_disk/latest' => 'compact_disk#latest', :as => :latest_cd
    match 'compact_disk/like/:id' => 'compact_disk#like', :as => :like_cd, :via => :get
    match 'comapct_disk/best' => 'compact_disk#best', :as => :best_cd, :via => :get
    match '/compact_disk/:id' => 'compact_disk#show', :as => :compact_disk, :via => :get
    match '/compact_disk/myCDs/:id' => 'compact_disk#myCDs', :as => :myCDs
    match 'compact_disk/swap/:id' => 'compact_disk#swap', :as => :swap_cd
    match '/compact_disk/all_user_cds/:id' => 'compact_disk#all_user_cds', :as => :allUserCDs
    match 'compact_disk/makeVisible/:id' => 'compact_disk#makeVisible', :as => :makeVisible
    match 'compact_disk/:id' => 'compact_disk#destroy', :as => :delete_cd, :via => :delete

    
    match 'transaction/history' => 'transaction#history', :as => :history
    resources :transaction
    match 'transaction/destroy_sent_msg/:id' => 'transaction#destroy_sent_msg', :as => :destroy_sent_msg
    match 'transaction/destroy/:id' => 'transaction#destroy', :as => :destroy
    match 'transaction/rejected/:id' => 'transaction#rejected', :as => :rejected
    match 'transaction/accept/:id' => 'transaction#accept', :as => :accept
    match 'transaction/accepted/:id' => 'transaction#accepted', :as => :accepted
    match 'transaction/modifyAccept/:id' => 'transaction#modifyAccept', :as => :modified_accept
    match 'transaction/modifyAccepted/:id' => 'transaction#modifyAccepted', :as => :modify_accepted
    match 'transaction/modifyReject/:id' => 'transaction#modifyReject', :as => :modified_reject
    match 'transaction/modifyRejected/:id' => 'transaction#modifyRejected', :as => :modified_rejected
    match 'transaction/modify/:id' => 'transaction#modify', :as => :modify, :via => :post
    match 'transaction/modifyRequest/:id' => 'transaction#modifyRequest', :as => :modifyRequest
    
    
    
    match 'impressum' => "application#impressum", :as => :impressum
    match 'admin/manage_users' => 'admin#manage_users', :as => :adminAllUsers
    match 'admin/manage_cds' => 'admin#manage_cds', :as => :adminAllCDs
  end
  

  

end

app/controllers/compact_disk_controller.rb
require 'rbrainz'
include MusicBrainz

class CompactDiskController < ApplicationController
  before_filter :set_locale
  before_filter :checkUser, :only =>[:destroy, :update]
  before_filter :signed_in?, :only => [:show]
  #load_and_authorize_resource :only => [:show, :destroy]
  
  def signed_in?
    unless user_signed_in?
      flash[:alert] = "Als Gast koennen sie sich die CD nicht ansehen!"
      redirect_to :back
    end
  end
  
  # Eigentümer des CD Prüfen
  def checkUser
     @cd = CompactDisk.find(params[:id])
     unless (@cd.user_id == current_user.id || AdminController.isAdmin(current_user))
       flash[:error] = "Dies ist nicht Ihre CD"
       redirect_to welcome_path
     end
  end
  
  def index
    #@cds = CompactDisk.where(:user_id => current_user.id)
    #@cds = CompactDisk.all
    if user_signed_in?
      @cds = CompactDisk.where('user_id != ?', current_user.id).paginate(:page => params[:page], :per_page => 10)
      #CompactDisk.where('user_id != ? AND in_transaction == ? AND visible == ?', current_user.id, false, true).order("id DESC").limit(10)
    else
      @cds = CompactDisk.paginate(:page => params[:page], :per_page => 10)
    end
  end
  
  def myCDs
    #@allCDs = CompactDisk.all
   # @myCDs = CompactDisk.where(:user_id => current_user.id)
    @myCDs = CompactDisk.where(:user_id => current_user.id).order("updated_at DESC").paginate(:page => params[:page], :per_page => 25)

  end
  
  def show
    @cd = CompactDisk.find(params[:id])
    #@songs = Song.where(:compact_disk_id => @cd.id)
    @songs = @cd.songs
    @user = User.find(@cd.user_id)
    
    if current_user.last_like == nil
      current_user.update_attribute(:last_like, Time.now-60*60)
    end
    
  end
  
  def destroy
    @cd = CompactDisk.find(params[:id])
    disk_user = User.find(@cd.user_id)
    
    # path to songs
    path = @cd.audio.path
    if !@cd.audio_file_name.nil?
      filename_with_ext = @cd.audio_file_name.gsub( /[^a-zA-Z0-9_\.]/, '_')
      path = path.chomp(filename_with_ext)
    end
    
    if (@cd.user_id == current_user.id)
      redirect_to myCDs_path
    else
      user = User.find(@cd.user_id)
      if (user.email_notification)
        
        params = {
          'method' => 'deletion_confirmation_compact_disk',
          'email' => user.email,
          'title' => @cd.title,
          'artist' => @cd.artist
        }
        
        Resque.enqueue(Email, params)
        #Notifier.deletion_confirmation_compact_disk(user.email, @cd.title, @cd.artist).deliver
      end
      redirect_to adminAllCDs_path
    end
    
    # Löschen aller Nachrichten zu der CD
    sent = disk_user.sent_messages.find(:all, :conditions => ["subject LIKE '%?%'", @cd.id])
    received = disk_user.received_messages.find(:all, :conditions => ["subject LIKE '%?%'", @cd.id])
    @sended = false
    @rvd = false
    
    sent.each do |s|
      cd_array = s.subject.split(';')
      split_array = cd_array[0].split(',')
      if (cd_array.include?(@cd.id.to_s))
        s.destroy
      end
    end
    
    received.each do |s|
      cd_array = s.subject.split(';')
      split_array = cd_array[0].split(',')
      if(cd_array.include?(@cd.id.to_s))
        s.destroy
      end
    end
    
    system("rm -rf #{path}")
    title = @cd.title
    @cd.destroy  
    flash[:notice] = "CD: "+title+" erfolgreich geloescht."
  end
  
  def new
    logger.debug 'call new'
    @cd = CompactDisk.new
    logger.debug 'new CD'
    @cd.songs.build
    #1.times { @cd.songs.build }
  end
  
  def mbrainz
    #logger.debug 'call mbrainz'
    map = searchMBrainz(params[:artist], params[:title])
    @tracks = map[:tracks]
    logger.debug "cover url: "+map[:cover_url]
    @tr = @tracks.to_a.map! {|t| Hash[value: t]}
    #respond_to do |format|
     # format.html
      #format.js
    #end
    render xml: map
    
  end
  
  def create
    @cd = CompactDisk.new(params[:compact_disk])
    
    # lade Tracks von MusicBrainz
    #tracks = searchTracks(@cd.artist, @cd.title)
    #logger.debug 'tracks' +tracks.to_s
    
    #@songs = (params[:song])  
    respond_to do |format|
        if @cd.save
          # save songs from musicBrianz
          #if !tracks.nil?
          #  tracks.each { |t| 
          #    logger.debug "erstelle Song: "+t.to_s
          #    song = Song.new(:title => t.to_s, :compact_disk_id => @cd.id)
          #    song.save
          #  }
          #end
          
          # try to convert to ogg if needed
          @cd.convert_to_ogg
          #@cd.update_attribute(:audio_file_name, @cd.audio_file_name+".ogg")
          #@cd.update_attribute(:audio_content_type, "audio/ogg")
          #logger.debug "new audio path"+@cd.audio.path
          
          format.html  { redirect_to(myCDs_path(current_user.id),
                        :notice => 'CD erfolgreich angelegt.') }
          format.json  { render :json => @cd,
                        :status => :created, :location => @cd }
          
        #  @songs.each do |s|
         #     @song  = Song.new(:compact_disk_id => @cd.id, :title => s[1])
          #    @song.save
          #end
        else
          format.html  { render :action => "new" }
          format.json  { render :json => @cd.errors,
                        :status => :unprocessable_entity }
        end
      end
  end
  
  def edit
    @cd = CompactDisk.find(params[:id])
    #@songs = Song.where(:compact_disk_id => @cd.id)
    #@cd.songs.build
    
  end
  
  def update
    @cd = CompactDisk.find(params[:id])
#    @songs = params[:song]
#    .except(:song)
    respond_to do |format|
      if @cd.update_attributes(params[:compact_disk])
        @cd.convert_to_ogg
        #allsongs = Song.where(:all, :compact_disk_id => @cd.id)
        #allsongs.each do |as|
        #  if as.id == params[:song][:index]
        #    as.title = params[:song]['1'][:title]
        #    as.save
        #  end
        #end
        flash[:notice] = "CD erfolgreich geaendert."
        format.html { redirect_to action: "show" }
      else
        format.html { render action: "edit" }
      end
    end
  end
  
  #def find_by_artist
  #  @cd = CompactDisk.where
  #end
  
  def swap
    if (!user_signed_in?)
      redirect_to welcome_path
    else
      @cd = CompactDisk.find(params[:id])
      @user = User.find(@cd.user_id)
      @userCDs = CompactDisk.where(:user_id => @cd.user_id)
      @myCDs = CompactDisk.where(:user_id => current_user.id)
    end
  end
  
  
  
  # get the last 10 Disks
  def latest
    if (user_signed_in?)
      
      # get all cds those are not mine and those are not in an transaktion
      @cds = CompactDisk.where('user_id != ?', current_user.id).order("created_at DESC").limit(10)#.paginate(:page => params[:page], :per_page => 9)
      #logger.debug "current_user.id = "+current_user.id.to_s
      #while @cds.size > 10 do
      #  @cds.pop
      #end
    else
      @cds = CompactDisk.order("id DESC").limit(10)#.paginate(:page => params[:page], :per_page => 9)
    end
  end
  
  # Anzeigen aller CDs einez Nutzers + Nutzerinformationen
  def all_user_cds
    @cds = CompactDisk.where(:user_id => params[:id]).paginate(:page => params[:page], :per_page => 10)
    @user = User.find(params[:id])
  end
  
  # Sichtbarkeit einer CD ändern
  def makeVisible
    @cd = CompactDisk.find(params[:id])
    @user = User.find(@cd.user_id)

    @sent_msg = @user.sent_messages(:all)
    @received_msg = @user.received_messages(:all)
=begin
    @in_transaction = false
        
    @sent_msg.each do |sm|
      if sm.subject.include?(@cd.id.to_s)
        @in_transaction = true
        break
      end
    end
    
    @received_msg.each do |rm|
      if rm.subject.include?(@cd.id.to_s)
        @in_transaction = true
        break
      end
    end
=end    
    if !@cd.in_transaction
      @cd.visible = true
      @cd.save
      redirect_to myCDs_path
    else
      flash[:error] = "CD befindet sich in einer Transaktion und kann nicht Freigegeben werden"
      redirect_to myCDs_path
    end
  end
  
  def like
    cd = CompactDisk.find(params[:id])
    
    user = User.find(current_user.id)
      if user.last_like < (Time.now-60*60)
        # es ist mehr als 1 Stunde seit dem letzten like vergangen
        user.update_attribute(:last_like, Time.now+60*60)
        cd.update_attribute(:rank,(cd.rank+1))
      end
    redirect_to :back
  end
  
  def best
    @best = CompactDisk.order("rank DESC").limit(10)
  end
  
  # Songs eines Albums
  def searchMBrainz(art, alb)
    query = Webservice::Query.new
    filter = Webservice::ReleaseFilter.new(:title => alb, :artist => art)
    release = query.get_releases(filter)
    if (!release.empty?)
      # get mbid of first
      mbid = release.entities[0].id.to_s;
      
      logger.debug "size of entities: "+release.entities.length.to_s
      #if release.entities[1] != nil
      #  mbid = release.entities[1].id.to_s;
      #end
    
      entities = release.entities
      asin = ""
      year = nil
      tracks = nil
      
      entities.each { |e|
        logger.debug "next entity"
        mbid = e.id.to_s
        r = query.get_release_by_id(mbid, :artist=>true, :tracks=>true, :release_events => true)
        if (!r.asin.nil?)
          asin = r.asin.to_s
          if year.nil?
            year = r.release_events[0].date.year
          end
          if tracks.nil?
            tracks = r.tracks
          end
          break
        end
      }
      
      
      logger.debug 'url_rels: '+release.to_s
      logger.debug "asin: "+asin
      
      #releations = release.get_relations( :relation_type => MusicBrainz::Model::NS_REL_1 + 'AmazonAsin' )
      #id = nil
      #p releations.map {|r| logger.debug "targeT: " +r.target}
      
      #logger.debug "id: "+id
      cover_url = nil
      unless asin.nil?
        cover_url = generate_cover_url(asin)
      else
        cover_url = ""
      end
      
      logger.debug "cover url: "+cover_url
      
      #logger.debug "r.target"+releations.artist

app/helpers/compact_disk_helper.rb
module CompactDiskHelper
  def existingTransactions(cd_id, user_id)
    user = User.find(user_id)
    cd = CompactDisk.find(cd_id)
    
    sent = user.sent_messages.find(:all, :conditions => ["subject LIKE '%?%'", cd])
    received = user.received_messages.find(:all, :conditions => ["subject LIKE '%?%'", cd])
    @sended = false
    @rvd = false
    
    sent.each do |s|
      cd_array = s.subject.split(';')
      split_array = cd_array[0].split(',')
      if (cd_array.include?(cd_id.to_s))
        @sended = true
        break
      end
    end
    
    received.each do |s|
      cd_array = s.subject.split(';')
      split_array = cd_array[0].split(',')
      if(cd_array.include?(cd_id.to_s))
        @rvd = true
        break
      end
    end
    
    return (@sended || @rvd)
  end
end

app/views/compact_disk/_song_partial.html.erb
<div class="input fields">
	<%= f.text_field :title %>
	<%= f.hidden_field :_destroy %> 
	<%= link_to_function '<span class="label important"> - </span>'.html_safe, 'remove_fields(this)', :class=> "rmSongBt" %>
</div>

app/views/compact_disk/all_user_cds.html.erb
<% content_for :title, t('.headline')+" "+@user.firstname+" "+@user.lastname %>

<div style="margin-left:20px;">
<% if flash[:alert] || flash[:notice] %>
	<div class="alert-message error">
		<a class="alert_close" href="#">×</a>
		<%= flash[:alert] %>
		<%= flash[:notice] %>
	</div>
<% end %>
</div>

<%= render "user/show_partial" %>

<!--<div id="usercds" class="box-swap" >-->
<%= will_paginate @cds, :previous_label => "Zurück", :next_label => "Weiter" %>	
<div class="row">
	<!--<h3>CD's des Users: </h3>-->
<ol id="selectable">
	<% @cds.each do |c| %>
	<li>
		<%= link_to (image_tag c.photo.url(:normal)), compact_disk_path(c), :rel=>"popover", :title=>c.title+" ("+c.artist+")", :id=>getSongs(c)%>
		
		<div class="blackFont"><%= c.artist %></div>
		<p class="line_height08"><%= c.title %></p>
		<p>
			<% if user_signed_in? && !c.in_transaction && c.visible %>
				<%= link_to t('.share'), swap_cd_path(c.id) %>
			<% end %>
			<% if user_signed_in? && c.in_transaction %>
				<span class="label warning line_height1"><In einer Transaktion><%= t('.label_transaction')%></span></br>
			<% end %>
		</p>
	</li>
	<% end %>
</ol>
</div>
<%= will_paginate @cds, :previous_label => "Zurück", :next_label => "Weiter"  %>	
<!--</div>-->

app/views/compact_disk/best.html.erb
<% content_for :title, t('.headline') %>

<div style="margin-left:20px;">
<% if flash[:alert]%>
	<div class="alert-message error">
		<a class="alert_close" href="#">×</a>
		<%= flash[:alert] %>
	</div>
<% end %>
</div>

<%
=begin %>
	<% if can?(:show, c) && user_signed_in? %>
		<%= link_to 'Show', c %>
	<% end %>
	<% if can?(:manage, c) && user_signed_in?%>
		<%= link_to 'Destroy', c, :confirm => 'Are you sure?', :method => :delete %>
	<% end %>
<%


<%
=end %>
<div style="height:494px;">
<ol id="selectable">
	<% @best.each do |c| %>
	<li>
		<!--<%= image_tag c.photo.url(:normal) %>-->
		<% if user_signed_in? %>
			<% if current_user.id == c.user_id %>
				<%= link_to (image_tag c.photo.url(:normal)), myCDs_path(c.user_id), :rel=>"popover", :title=>c.title+" ("+c.artist+")", :id=>getSongs(c)%>
			<% else %>
				<%= link_to (image_tag c.photo.url(:normal)), compact_disk_path(c), :rel=>"popover", :title=>c.title+" ("+c.artist+")", :id=>getSongs(c)%>
			<% end %>
		<% end %>
		<% if !user_signed_in? %>
			<%= link_to (image_tag c.photo.url(:normal)), allUserCDs_path(c.user_id), :rel=>"popover", :title=>c.title+" ("+c.artist+")", :id=>getSongs(c)%>
		<% end %>
		<div class="blackFont"><%= c.artist %></div>
		<p class="line_height08"><%= c.title %></p>
		<p>
			<!--<%= link_to 'Show', compact_disk_path(c) %>-->
			<% if user_signed_in? && !c.in_transaction && c.visible %>
				<%= link_to t('.share'), swap_cd_path(c.id) %>
			<% end %>
			<% if user_signed_in? && c.in_transaction %>
				<span class="label warning line_height1"><%= t('.label_transaction')%></span></br>
			<% end %>
		</p>
	</li>
	<% end %>
</ol>
</div>

app/views/compact_disk/index.html.erb
<% content_for :title, t('.cd_all') %>

<div style="margin-left:20px;">
<% if flash[:alert]%>
	<div class="alert-message error">
		<a class="alert_close" href="#">×</a>
		<%= flash[:alert] %>
	</div>
<% end %>
</div>

<%
=begin %>
	<% if can?(:show, c) && user_signed_in? %>
		<%= link_to 'Show', c %>
	<% end %>
	<% if can?(:manage, c) && user_signed_in?%>
		<%= link_to 'Destroy', c, :confirm => 'Are you sure?', :method => :delete %>
	<% end %>
<%


<%
=end %>
<div style="padding-left:20px;">
<%= will_paginate @cds, :next_label => t('.paginate_further'), :previous_label => t('.paginate_back') %>
</div>
<div style="height:494px;">
<ol id="selectable">
	<% @cds.each do |c| %>
	<li>
		<!--<%= image_tag c.photo.url(:normal) %>-->
		<% if user_signed_in? %>
			<%= link_to (image_tag c.photo.url(:normal)), compact_disk_path(c), :rel=>"popover", :title=>c.title+" ("+c.artist+")", :id=>getSongs(c)%>
		<% else %>
			<%= link_to (image_tag c.photo.url(:normal)), allUserCDs_path(c.user_id), :rel=>"popover", :title=>c.title+" ("+c.artist+")", :id=>getSongs(c)%>
		<% end %>
		<div class="blackFont"><%= c.artist %></div>
		<p class="line_height08"><%= c.title %></p>
		<p>
			<!--<%= link_to 'Show', compact_disk_path(c) %>-->
			<% if user_signed_in? && current_user.id != c.user_id && !c.in_transaction && c.visible %>
				<%= link_to t('.share'), swap_cd_path(c.id) %>
			<% end %>
			<% if user_signed_in? && c.in_transaction %>
				<span class="label warning line_height1"><%= t('.label_transaction')%></span></br>
			<% end %>
		</p>
	</li>
	<% end %>
</ol>
</div>
<div class="row">
	<div style="padding-left:20px;">
	<%= will_paginate @cds, :next_label => t('.paginate_further'), :previous_label => t('.paginate_back')  %>
	</div>
</div>

app/views/compact_disk/new.html.erb
<% content_for :title, t('.headline') %>

<% if @cd.errors.any? %>
    <div class="alert-message block-message error" style="margin-left:17px;">
      <ul>
        <% @cd.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for @cd, :url => { :action => "create" } do |f| %>


	<%= render 'form_fields', :form => f %>

    <div class="actions"> 
        <%= f.submit "CD erstellen", :class => "btn success" %>
    </div>
<% end %>

<div class="result"></div>

app/views/compact_disk/show.html.erb
<% content_for :title, @cd.title+" ("+@cd.artist+")" %>
<div style="margin-left:20px;">
<% if flash[:notice] %>
	<div class="alert-message success">
		<a class="alert_close" href="#">×</a>
		<%= flash[:notice] %></p>
	</div>
<% end %>
</div>

<div class="row show-grid" >
	<div class="span11" style="margin-left:39px;">
		
		<% if !user_signed_in? || current_user.id != @cd.user_id %>
			<p>
				<b><%= t('.owner')%></b>
				<%= link_to @user.firstname + ' ' + @user.lastname, allUserCDs_path(@cd.user_id) %>
			</p>
		<% end %>
		
		<% if !@cd.genre.empty?%>
			<p>
				<b><%= t('.genre')%></b>
				<%= @cd.genre %>
			</p>
		<% end %>
		
		<% if @cd.year != nil %>
			<p>
				<b><%= t('.year')%></b>
				<%= @cd.year %>
			</p>
		<% end %>
		
		<% if !@cd.description.empty? %>
			<p>
				<b><%= t('.description')%></b>
				<%= @cd.description %>
			</p>
		<% end %>

		<% if !@songs.empty?%>
			<p>
			<b>Songs:</b><br/>
			<% @songs.each_with_index do |s, index| %>
				<%= index + 1 %>
				<%= s.title %>
				</br>
			<% end %>
			</p>
		<% end %>	
		
		<% if @cd.audio_file_name != nil %>
			
			<p>
			<b>DemoSong:</b>
				<% if @cd.song_being_converted %>
					Song wird gerade konvertiert...
				<% else %>
					<%= @cd.last_audio_file_name%> 
					
					<p> <audio controls="controls">
						<!-- Dateiname ohne Extension -->
						<% filename = File.basename(@cd.audio_file_name, File.extname(@cd.audio_file_name).downcase)%>
						<% path = @cd.audio.url.chomp(@cd.audio_file_name) %>
						<!-- MP3 -->
						<source src=<%='"'.html_safe+ path+filename+'.mp3"'.html_safe %> type=<%='"audio/mp3"'.html_safe %>  />

						<!-- Ogg-->	
						<source src=<%='"'.html_safe+ path+filename+'.ogg"'.html_safe %> type=<%='"audio/ogg"'.html_safe %>  />
					  Your browser does not support the audio element.
					</audio>
					</p>
				<% end %>
			</p>
			
			
		<% end %>
		
		<p>
			<b><%= t('.stars')%></b> <%= @cd.rank.to_s %> 
			<% if current_user.id != @cd.user_id && current_user.last_like != nil && current_user.last_like < (Time.now-60*60) %>
				(<%= link_to 'Like', like_cd_path(@cd.id) %>)
				<span class="span6 offset10">
	          <%= image_tag ("information-white.png"), :class=>"information_symbol", :rel=>"popover", :title => 'Like', :id => "Wenn Sie eine CD mögen können sie mit dem Like Button einen Stern vergeben."  %>
	      </span>
			<% end %>
			<% if current_user.id != @cd.user_id && current_user.last_like != nil && current_user.last_like > (Time.now-60*60) %>
			<span class="span6 offset10">
          <%= image_tag ("information-white.png"), :class=>"information_symbol", :rel=>"popover", :title => 'Like', :id => "Sie können nur alle zwei Stunde eine CD liken."  %>
      </span>
			<% end %>
		</p>
		
	</div>
	<div class="span5">
        <%= image_tag @cd.photo.url(:normal) %>
    </div>
</div>

<div class="row show-grid">
	
	<div class="actions"> 
	<% if user_signed_in? && @cd.user_id == current_user.id%>
		<%= link_to t('.button_back'), myCDs_path, :class => "btn default" %>
		<%= link_to t('.button_edit'), edit_compact_disk_path(@cd), :class => "btn primary" %>
		
		<% if @cd.audio_file_name != nil %>
		<div style=" float:right;">
			<%= link_to t('.delete_song'), delete_demo_songs_path(@cd), :class => "btn danger", :remote => true, 'data-controls-modal' =>  "modal-window", 'data-backdrop' => true, 'data-keyboard' => true  %>
		</div>
		<% end %>
	<% else %>
		<%= link_to 'Showcase', allUserCDs_path(@cd.user_id), :class => "btn default" %>
		<% if user_signed_in? %>
			<!--<% if current_user.id != @cd.user_id %>
				<%= link_to 'Like', like_cd_path(@cd.id), :class => "btn success" %>
			<% end %>-->
			
			<% if !@cd.in_transaction && @cd.visible %>
				<%= link_to t('.share'), swap_cd_path(@cd.id), :class => "btn primary" %>
			<% end %>
		<% end %>
		<% if user_signed_in? && AdminController.isAdmin(current_user) %>
			<div style=" float:right;">
			<% if @cd.audio_file_name != nil %>
				<%= link_to "Song löschen", @cd, :class => "btn danger", :remote => true, 'data-controls-modal' =>  "modal-window", 'data-backdrop' => true, 'data-keyboard' => true %>
			<% end %>
		
			
				<%= link_to t('.delete_cd'), @cd, :confirm => "Wollen die CD \""+ @cd.title+"\" von "+User.find(@cd.user_id).firstname+" "+User.find(@cd.user_id).lastname+" wirklich löschen?", :method => :delete, :class => "btn danger" %>
			</div>
		<% end %>
	<% end %>
	
	<div class="modal hide fade" id="modal-window">
	  <div class="modal-header">
	    <a href="#" class="close">×</a>
	    <h3>Song löschen</h3>
	  </div>
	  <div class="modal-body center">
			Wollen Sie den Song <b><%= @cd.last_audio_file_name%></b> wirklich löschen?
	  </div>
	  <div class="modal-footer">
	  	<%= link_to "Ja Song löschen", delete_demo_songs_path(@cd), :class => "btn danger", :method => :delete %>
	  </div>
	</div>
	
	</div>
	
	
</div>