config/routes.rb
Projekt::Application.routes.draw do
  devise_for :users
  
  mount Resque::Server, :at => "/resque"
   

  
  
    
    
    match '/search' => 'application#search', :as => :search
  
  match '/autoCompl' => 'application#autoCompl', :as => :autoCompl
  
  scope "(:locale)", :locale => /de|en/ do
    root :to => 'welcome#index', :as => :welcome
    
    resources :user, :except => [:show, :destroy]
    match '/user/most_active' => 'user#most_active', :as => :most_active_user
    match 'user/reset_password' => 'user#reset_password', :as => :reset_password
    match '/user/setAdmin/:id' => 'user#set_as_admin', :as => :set_as_admin, :via => :get
    match '/user/setUser/:id' => 'user#set_as_user', :as => :set_as_user, :via => :get
    match '/user/:id' => 'user#show', :as => :user, :via => :get
    match '/user/:id' => 'user#destroy', :as => :delete_user, :via => :delete
   
    
    resources :devise
    match 'compact_disk/mbrainz/' => 'compact_disk#mbrainz', :as => :mbrainz, :via => :get
    
    resources :compact_disk, :except => [:show, :destroy]
    match '/comapct_disk/delete_demo_songs:id' => 'compact_disk#delete_demo_songs', :as => :delete_demo_songs, :via => :delete
    match '/compact_disk/latest' => 'compact_disk#latest', :as => :latest_cd
    match 'compact_disk/like/:id' => 'compact_disk#like', :as => :like_cd, :via => :get
    match 'comapct_disk/best' => 'compact_disk#best', :as => :best_cd, :via => :get
    match '/compact_disk/:id' => 'compact_disk#show', :as => :compact_disk, :via => :get
    match '/compact_disk/myCDs/:id' => 'compact_disk#myCDs', :as => :myCDs
    match 'compact_disk/swap/:id' => 'compact_disk#swap', :as => :swap_cd
    match '/compact_disk/all_user_cds/:id' => 'compact_disk#all_user_cds', :as => :allUserCDs
    match 'compact_disk/makeVisible/:id' => 'compact_disk#makeVisible', :as => :makeVisible
    match 'compact_disk/:id' => 'compact_disk#destroy', :as => :delete_cd, :via => :delete

    
    match 'transaction/history' => 'transaction#history', :as => :history
    resources :transaction
    match 'transaction/destroy_sent_msg/:id' => 'transaction#destroy_sent_msg', :as => :destroy_sent_msg
    match 'transaction/destroy/:id' => 'transaction#destroy', :as => :destroy
    match 'transaction/rejected/:id' => 'transaction#rejected', :as => :rejected
    match 'transaction/accept/:id' => 'transaction#accept', :as => :accept
    match 'transaction/accepted/:id' => 'transaction#accepted', :as => :accepted
    match 'transaction/modifyAccept/:id' => 'transaction#modifyAccept', :as => :modified_accept
    match 'transaction/modifyAccepted/:id' => 'transaction#modifyAccepted', :as => :modify_accepted
    match 'transaction/modifyReject/:id' => 'transaction#modifyReject', :as => :modified_reject
    match 'transaction/modifyRejected/:id' => 'transaction#modifyRejected', :as => :modified_rejected
    match 'transaction/modify/:id' => 'transaction#modify', :as => :modify, :via => :post
    match 'transaction/modifyRequest/:id' => 'transaction#modifyRequest', :as => :modifyRequest
    
    
    
    match 'impressum' => "application#impressum", :as => :impressum
    match 'admin/manage_users' => 'admin#manage_users', :as => :adminAllUsers
    match 'admin/manage_cds' => 'admin#manage_cds', :as => :adminAllCDs
  end
  

  

end

app/views/admin/_manage_cd_partial.html.erb
<div style="margin-left:20px;">
<% if flash[:notice] %>
	<div class="alert-message success">
		<a class="alert_close" href="#">×</a>
		<%= flash[:notice] %></p>
	</div>
<% end %>
</div>

<%= will_paginate @cds, :previous_label => "Zurück", :next_label => "Weiter"  %>
<table class="bordered-table zebra-striped" style="margin-left:20px; width: 98% !important;">
    <colgroup>
    <col width="60"> <!-- Cover -->
	<col width="auto"> <!-- ID -->
    <col width="auto"> <!-- Artist -->
    <col width="auto"> <!-- Interpret-->
    <col width="auto"> <!-- Genre-->
    <col width="auto"> <!-- Beschreibung-->
	<col width="auto"> <!-- Eingestellt von-->
    <col width="auto"> <!-- Löschen -->
    </colgroup>
<thead>
<tr>
    <th>Cover</th>
	<th>ID</th>
    <th>Artist</th>
    <th>Interpret</th>
    <th> Genre</th>
    <th> Beschreibung</th>
	<th> Gehört</th>
    <th> Löschen </th>
</tr>
</thead>
<tbody>
<% @cds.each do |cd| %>
<tr>
    	<td><%= link_to (image_tag cd.photo.url(:small)), compact_disk_path(cd) %> </td>
		<td><%= cd.id %></td>
		<td><%= cd.title %></td>
		<td><%= cd.artist %></td>
    	<td><%= cd.genre %></td>
    	<td><%= cd.description %></td>
		<% user = User.find(cd.user_id) %>
		<% if user.alias.empty? %>
			<td><%= user.firstname + " "+ user.lastname %> </td>
		<% else %>
			<td><%= user.alias %> </td>
		<% end %>
		
    	<td><%= link_to (image_tag("cross-script.png")), delete_cd_path(cd.id), :method => :delete, :confirm => "Wollen sie diese CD wirklich löschen?" %> <br></td>
    <!--<td><%= image_tag("cross-script.png")%></td>-->
</tr>

<% end %>
</tbody>
</table>
<%= will_paginate @cds, :previous_label => "Zurück", :next_label => "Weiter"  %>

app/views/admin/_manage_user_partial.html.erb
<div style="margin-left:20px;">
<% if flash[:notice] %>
	<div class="alert-message success">
		<a class="alert_close" href="#">×</a>
		<%= flash[:notice] %></p>
	</div>
<% end %>
</div>

<br />
<table class="bordered-table zebra-striped" style="margin-left:20px; width: 98% !important;">
    <colgroup>
    <col width="60"> <!-- Bild -->
    <col width="auto"> <!-- Vorname -->
    <col width="auto"> <!-- Nachname-->
    <col width="auto"> <!-- Email-->
    <col width="auto"> <!-- Alias-->
	<% if user_signed_in? && AdminController.isAdmin(current_user) %>
		<col width="auto"> <!-- ID -->
	    <col width="auto"> <!-- Registrierdatum-->
		<col width="auto"> <!-- Letzter Login-->
	    <col width="auto"> <!-- Admin -->
	    <col width="auto"> <!-- Löschen -->
	<% end %>
    </colgroup>
<thead>
<tr>
    <th>Bild</th>
    <th>Vorname</th>
    <th>Nachname</th>
    <th> Email</th>
    <th> Alias</th>
	<% if user_signed_in? && AdminController.isAdmin(current_user) %>
		<th> ID </th>
	    <th> Registierdatum</th>
		<th> Letzter Login </th>
		<th> Admin </th>
	    <th> Löschen</th>
	<% end %>
</tr>
</thead>
<tbody>
<% @users.each do |u| %>
<tr>
    	<td><%= link_to (image_tag u.photo.url(:small)), allUserCDs_path(u.id) %></td>
		<td><%= u.firstname %></td>
		<td><%= u.lastname %></td>
    	<td><%= u.email %></td>
    	<td><%= u.alias %></td>
		<% if user_signed_in? && AdminController.isAdmin(current_user) %>
			<td><%= u.id %></td>
	    	<td><%= u.created_at.strftime("%d. %b. %Y") %></td>
			<td><%= u.last_sign_in_at.strftime("%d. %b. %Y") %></td>
			<td>
				<b>
				<% if u.role_id == User.admin %>
					ja
				<% else %>
				  nein
				<% end %>
				</b>
				<br><br>
				ändern zu:
				<% if u.role_id == User.admin %>
					<br>
					<%= link_to "User", set_as_user_path(u.id), :class => "btn default" %><br>
				<% end %>
				<% if u.role_id == User.user %>
					<br>
					<%= link_to "Admin", set_as_admin_path(u.id), :class => "btn default" %><br>
				<% end %>
			</td>
			<td> 	
				<%= link_to (image_tag("cross-script.png")), delete_user_path(u.id), :method => :delete, :confirm => "Wollen sie diesen Benutzer wirklich löschen?" %> <br>
			</td>
		<% end %>
    <!--<td><%= image_tag("cross-script.png")%></td>-->
</tr>
<% end %>




</tbody>
</table>

app/views/admin/manage_cds.html.erb
<% content_for :title, "CD Verwaltung" %>
<%= render "admin/manage_cd_partial" %>

app/views/admin/manage_users.html.erb
<% content_for :title, "Nutzerverwaltung" %>
<%= will_paginate @users, :previous_label => "Zurück", :next_label => "Weiter"  %>
<%= render "admin/manage_user_partial" %>
<%= will_paginate @users, :previous_label => "Zurück", :next_label => "Weiter"  %>