config/routes.rb
Projekt::Application.routes.draw do
  devise_for :users
  
  mount Resque::Server, :at => "/resque"
   

  
  
    
    
    match '/search' => 'application#search', :as => :search
  
  match '/autoCompl' => 'application#autoCompl', :as => :autoCompl
  
  scope "(:locale)", :locale => /de|en/ do
    root :to => 'welcome#index', :as => :welcome
    
    resources :user, :except => [:show, :destroy]
    match '/user/most_active' => 'user#most_active', :as => :most_active_user
    match 'user/reset_password' => 'user#reset_password', :as => :reset_password
    match '/user/setAdmin/:id' => 'user#set_as_admin', :as => :set_as_admin, :via => :get
    match '/user/setUser/:id' => 'user#set_as_user', :as => :set_as_user, :via => :get
    match '/user/:id' => 'user#show', :as => :user, :via => :get
    match '/user/:id' => 'user#destroy', :as => :delete_user, :via => :delete
   
    
    resources :devise
    match 'compact_disk/mbrainz/' => 'compact_disk#mbrainz', :as => :mbrainz, :via => :get
    
    resources :compact_disk, :except => [:show, :destroy]
    match '/comapct_disk/delete_demo_songs:id' => 'compact_disk#delete_demo_songs', :as => :delete_demo_songs, :via => :delete
    match '/compact_disk/latest' => 'compact_disk#latest', :as => :latest_cd
    match 'compact_disk/like/:id' => 'compact_disk#like', :as => :like_cd, :via => :get
    match 'comapct_disk/best' => 'compact_disk#best', :as => :best_cd, :via => :get
    match '/compact_disk/:id' => 'compact_disk#show', :as => :compact_disk, :via => :get
    match '/compact_disk/myCDs/:id' => 'compact_disk#myCDs', :as => :myCDs
    match 'compact_disk/swap/:id' => 'compact_disk#swap', :as => :swap_cd
    match '/compact_disk/all_user_cds/:id' => 'compact_disk#all_user_cds', :as => :allUserCDs
    match 'compact_disk/makeVisible/:id' => 'compact_disk#makeVisible', :as => :makeVisible
    match 'compact_disk/:id' => 'compact_disk#destroy', :as => :delete_cd, :via => :delete

    
    match 'transaction/history' => 'transaction#history', :as => :history
    resources :transaction
    match 'transaction/destroy_sent_msg/:id' => 'transaction#destroy_sent_msg', :as => :destroy_sent_msg
    match 'transaction/destroy/:id' => 'transaction#destroy', :as => :destroy
    match 'transaction/rejected/:id' => 'transaction#rejected', :as => :rejected
    match 'transaction/accept/:id' => 'transaction#accept', :as => :accept
    match 'transaction/accepted/:id' => 'transaction#accepted', :as => :accepted
    match 'transaction/modifyAccept/:id' => 'transaction#modifyAccept', :as => :modified_accept
    match 'transaction/modifyAccepted/:id' => 'transaction#modifyAccepted', :as => :modify_accepted
    match 'transaction/modifyReject/:id' => 'transaction#modifyReject', :as => :modified_reject
    match 'transaction/modifyRejected/:id' => 'transaction#modifyRejected', :as => :modified_rejected
    match 'transaction/modify/:id' => 'transaction#modify', :as => :modify, :via => :post
    match 'transaction/modifyRequest/:id' => 'transaction#modifyRequest', :as => :modifyRequest
    
    
    
    match 'impressum' => "application#impressum", :as => :impressum
    match 'admin/manage_users' => 'admin#manage_users', :as => :adminAllUsers
    match 'admin/manage_cds' => 'admin#manage_cds', :as => :adminAllCDs
  end
  

  

end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController

# neue Anfrage erstellen
def create
  cd_visible = true
 
  # User_ID des Tauschpartners
  user_id = params[:user_id]
  
  # Nachrichtentext
  body = params[:body]
 
  # CDs die getauscht werden sollen
  cd_mine = params[:cds_mine]
  cd_wanted = params[:cds_wanted]
 
  # einzelne CD IDs 
  seperated_mine_cds = cd_mine.split(',')
  seperated_wanted_cds = cd_wanted.split(',')
 
  # Nutzerdaten ermitteln
  user = User.find(current_user.id)
  dest = User.find(user_id)
  
  # CDs suchen die nicht Sichtbar sind
  @disks_mine = CompactDisk.where(:id => seperated_mine_cds, :in_transaction => true)
  @disks_wanted = CompactDisk.where(:id => seperated_wanted_cds, :in_transaction => true)

  # Anfrage nur erstellen wenn CD noch visible ist, d.h Arrays der vorherigen Abfrage sind leer
  if (@disks_mine.empty? || @disks_wanted.empty?)
    params = {
      'method' => 'new_offer',
      'email' => dest.email,
      'alias' => user.alias
    }
    
    Resque.enqueue(Email, params)
    #Notifier.new_offer(dest.email, user.alias).deliver
  
    message = Message.new
    message.subject = "#{cd_mine};#{cd_wanted}"
    message.body = "Anfrage"
    message.sender = user
    message.recipient = dest
    if message.save
      CompactDisk.update_all({:visible => false, :in_transaction => true}, {:id => seperated_mine_cds}) 
      CompactDisk.update_all({:visible => false, :in_transaction => true}, {:id => seperated_wanted_cds})        
      redirect_to transaction_index_path
    end
    else
      redirect_to :controller => "compact_disk", :action => "index"
      flash[:notice] = "Mindestens eine CD ist nicht mehr fuer einen Tausch verfuegbar"
    end
end

# Anfrage löschen/ablehnen
def destroy  
  msg_id = params[:id]

  msg = Message.find(msg_id)
  
  subj_splitted = msg.subject.split(';')
  cds_splitted = subj_splitted[0].split(',') + subj_splitted[1].split(',')   
  
  # user -> Nutzer der Nachricht (Anfrage) empfangen hat
  # dest -> Nutzer der benachrichtigt werden soll, dass Anfrage abgelehnt wurde
  user = msg.recipient_id
  dest = msg.sender_id 

  rsv_message = Message.read(msg_id, user)

  user = rsv_message.recipient
  dest = rsv_message.sender
  
  # Antwort an Sender das Anfrage abgelehnt wurde
  message = Message.new
  message.subject = rsv_message.subject
  message.body = "Abgelehnt; #{msg_id}"
  message.sender = user
  message.recipient = dest
  message.save
  
  # Nachrichten als gelöscht markieren; Sobald Empfänger dies auch macht, wird Nachricht gelöscht
  msg.mark_deleted(user)
  message.mark_deleted(user)
  
  CompactDisk.update_all({:visible => true, :in_transaction => false}, {:id => cds_splitted}) 

  redirect_to :action => "index"
end

def destroy_sent_msg
  msg_id = params[:id]

  msg = Message.find(msg_id)
  
  # user -> Nutzer der Nachricht (Anfrage) empfangen hat
  # dest -> Nutzer der benachrichtigt werden soll, dass Anfrage abgelehnt wurde
  user = msg.recipient_id
  dest = msg.sender_id 

  rsv_message = Message.read(msg_id, user)

  user = rsv_message.recipient
  dest = rsv_message.sender
  if !msg.body.include?('Modifikation')
    subj_splitted = msg.subject.split(';')
    cds_splitted = subj_splitted[0].split(',') + subj_splitted[1].split(',')   
    # Nachrichten als gelöscht markieren; Sobald Empfänger dies auch macht, wird Nachricht gelöscht
    msg.destroy
  
    CompactDisk.update_all({:visible => true, :in_transaction => false}, {:id => cds_splitted}) 
   
    redirect_to :action => "index"
  else
    splitted_body = msg.body.split(';')
    prev_msg_id = splitted_body[1]
    prev_msg = Message.find(prev_msg_id)
    
    subj_splitted = msg.subject.split(';')
    cds_splitted = subj_splitted[2].split(',') + subj_splitted[3].split(',')   
    # Nachrichten als gelöscht markieren; Sobald Empfänger dies auch macht, wird Nachricht gelöscht
    msg.destroy
    prev_msg.destroy
    CompactDisk.update_all({:visible => true, :in_transaction => false}, {:id => cds_splitted}) 
   
    redirect_to :action => "index"
  end
end

# Nachricht anzeigen
def index
  @user_id = current_user.id
  @user = User.find(@user_id)
  
  # Alle Anfrage
  @messages_accepted = @user.received_messages.find(:all, :conditions => ["read_at is ? and body LIKE '%Angenommen%'", nil])
  @messages_rejected = @user.received_messages.find(:all, :conditions => ["read_at is ? and body LIKE '%Abgelehnt%'", nil])
  @messages_requests = @user.received_messages.find(:all, :conditions => ["read_at is ? and body LIKE '%Anfrage%'", nil])
  @messages_modified = @user.received_messages.find(:all, :conditions => ["read_at is ? and body LIKE '%Modifikation%'", nil])
  @sent_messages = @user.sent_messages(:all);  

end

# Bestätigung der Absage
def rejected
  msg_id = params[:id]

  msg = Message.find(msg_id)
  
  splitted_body = msg.body.split(';')
  prev_msg_id = splitted_body[1]
  
  # current_user?
  msg_user = User.find(msg.recipient_id)
  
  subject = msg.subject

  # Aktuelle Nachricht als gelesen markieren
  rsv_message = Message.read(msg_id, msg_user)
  
  # Vorgänger Nachricht
  #sent_message = msg_user.sent_messages.find(:all, :conditions => ["sender_id = ? and subject = ? and body LIKE '%Anfrage%'", msg_user.id, subject])
  
  sent_message = msg_user.sent_messages.find(prev_msg_id)
  
  user = rsv_message.recipient
  #dest = rsv_message.sender
  
#  msg.mark_deleted(user)
#  sent_message.mark_deleted(user)
  msg.destroy
  sent_message.destroy

  redirect_to :action => "index"
end

# Anfrage annehmen
def accept  
  #user = params[:user_id]
  msg_id = params[:id]

  msg = Message.find(msg_id)
  user = msg.recipient_id
  #dest = msg.recipient_id
  dest = msg.sender_id 
  #user = msg.sender_id 

  rsv_message = Message.read(msg_id, user)

  cds = rsv_message.subject

  cd_array = cds.split(';')

  tauschCDs = cd_array[0].split(',')
  wunschCDs = cd_array[1].split(',')

  user = rsv_message.recipient
  dest = rsv_message.sender
  message = Message.new
  message.subject = rsv_message.subject
  message.body = "Angenommen; #{msg_id}"
  message.sender = user
  message.recipient = dest
  message.save

#  user = User.find(user)
#  dest = User.find(dest)
  
  # CDs suchen die nicht mehr sichtbar (verfügbar) sind
  @tausch_visible = CompactDisk.where(:id => tauschCDs, :visible => false)
  @wunsch_visible = CompactDisk.where(:id => wunschCDs, :visible => false)
  
  still_myCDs = CompactDisk.where(:id => tauschCDs, :user_id => current_user.id)

  #if @tausch_visible.empty? && @wunsch_visible.empty? && (still_myCDs.size == tauschCDs.size)
    # Transaktion erstellen
    t = Transaction.new(:provider_id => dest.id, :receiver_id => user.id)
    t.save
    logger.debug("Transaction-ID: #{t.id}")

    CompactDisk.update_all({:user_id => user.id, :visible => true, :in_transaction => false}, {:id => tauschCDs})
    CompactDisk.update_all({:user_id => dest.id, :visible => true, :in_transaction => false}, {:id => wunschCDs})
      
    tauschCDs.each do |tcd|
      sp = SwapProvider.new(:transaction_id => t.id, :compact_disk_id => tcd.to_i)
      sp.save
    end
    
    wunschCDs.each do |wcd|
      sr = SwapReceiver.new(:transaction_id => t.id, :compact_disk_id => wcd.to_i)
      sr.save
    end
    

    # Nachrichen löschen
    msg.mark_deleted(user)
    message.mark_deleted(user)

    redirect_to :action => "index"
  #else
   # redirect_to :action => "index"
    #flash[:notice] = "Mindestens eine der CDs ist nicht mehr verfuegbar"
    #msg.mark_deleted(user)
    #message.mark_deleted(user)
  #end
end

# Bestätigung der Annahme
def accepted
  msg_id = params[:id]

  msg = Message.find(msg_id)
  #user = msg.recipient_id
  msg_user = User.find(msg.recipient_id)
  dest = msg.sender_id 
  subject = msg.subject

  # subject von zuerst empfangender mail
  rsv_message = Message.read(msg_id, msg_user.id)
  sent_message = msg_user.sent_messages.find(:all, :conditions => ["sender_id = ? and subject = ? and body LIKE '%Anfrage%'", msg_user.id, subject])

  user = rsv_message.recipient
  #dest = rsv_message.sender

  msg.mark_deleted(user)
  sent_message[0].mark_deleted(user)
  
  redirect_to :action => "index"
end

# Daten aktueller Anfrage abrufen, um diese zu modifizieren
def modifyRequest
  @msg_id = params[:id]
  msg = Message.find(@msg_id)
  @msg_subject = msg.subject
  
  @user = User.find(msg.sender_id)
  @userCDs = CompactDisk.where(:user_id => @user.id, :visible => true, :in_transaction => false)
  
  @myCDs = CompactDisk.where(:user_id => current_user.id, :visible => true, :in_transaction => false)
end

def modify
  #user = params[:user_id]
  #msg_id = params[:id]
  msg_id = params[:msg_id]
  #prev_msg_id = params[:prev_msg_id]
  
  # Modifiezierte Anfrage
  modified_mine = params[:cds_wanted]
  modified_wanted = params[:cds_mine]
  
  splitted_mine = modified_mine.split(',')
  splitted_wanted = modified_wanted.split(',')
    
  msg = Message.find(msg_id)
  
  # Empfänger Org. Message ist jest der Sender
  user = msg.recipient_id
  # Sender der Org. Message ist jetzt Empfänger der neuen Nachricht
  dest = msg.sender_id 

  # subject von zuerst empfangender mail
  rsv_message = Message.read(msg_id, user)

  user = rsv_message.recipient
  dest = rsv_message.sender
  message = Message.new
  message.subject = rsv_message.subject + ";#{modified_mine};#{modified_wanted}"
  message.body = "Modifikation; #{msg_id}"
  message.sender = user
  message.recipient = dest
  message.save
  
  cds_old = msg.subject
  cd_array = cds_old.split(';')

  tauschCDs_old = cd_array[0].split(',')
  wunschCDs_old = cd_array[1].split(',')

  CompactDisk.update_all({:visible => true, :in_transaction => false}, {:id => tauschCDs_old})
  CompactDisk.update_all({:visible => true, :in_transaction => false}, {:id => wunschCDs_old})

  
  CompactDisk.update_all({:visible => false, :in_transaction => true}, {:id => splitted_mine})
  CompactDisk.update_all({:visible => false, :in_transaction => true}, {:id => splitted_wanted})
  

app/helpers/transaction_helper.rb
module TransactionHelper
  def getWantedCDs(cds)
    cd_array = cds.split(';')
    return cd_array[0].split(',')
  end
  
  def getMineCDs(cds)    
      cd_array = cds.split(';')
      return cd_array[1].split(',')
  end
  
  def getCover(cd)
    disk = CompactDisk.find(cd.to_i)
    return disk
  end
  
  def getCD(cd)
    disk = CompactDisk.find(cd.to_i)
    return disk
  end
  
  def getOldReqMine(cds)
    cd_array = cds.split(';')
    return cd_array[0].split(',')
  end
  
  def getOldReqProvide(cds)
    cd_array = cds.split(';')
    return cd_array[1].split(',')
  end

  def getNewReqMine(cds)
    cd_array = cds.split(';')
    return cd_array[2].split(',')
  end
  
  def getNewReqProvide(cds)
    cd_array = cds.split(';')
    return cd_array[3].split(',')
  end
  
  def isRejected?(msg_id)
    status_rejected = current_user.received_messages.find(:all, :conditions => ["body LIKE ?", "Abgelehnt; #{msg_id}%"])
    return !status_rejected.empty?
  end
  
  def getRejectedMsg(msg_id)
    status_rejected = current_user.received_messages.find(:all, :conditions => ["body LIKE ?", "Abgelehnt; #{msg_id}%"])
    return status_rejected[0]
  end

  def getAcceptedMsg(msg_id)
     status_accepted = current_user.received_messages.find(:all, :conditions => ["body LIKE ?", "Angenommen; #{msg_id}%"])
     return status_accepted[0]
   end

  def getModifiedMsg(msg_id)
     status_modified= current_user.received_messages.find(:all, :conditions => ["body LIKE ?", "Modifiziert; #{msg_id}%"])
     return status_modified[0]
   end

  def isModified?(msg_id)
    status_modified = current_user.received_messages.find(:all, :conditions => ["body LIKE ?", "Modifikation; #{msg_id}%"])
    return !status_modified.empty?
  end
  
  def isAccepted?(msg_id)
    status_modified = current_user.received_messages.find(:all, :conditions => ["body LIKE ?", "Angenommen; #{msg_id}%"])
    return !status_modified.empty?
  end
  
  def isModAccepted?(msg_id)
     status_modAccepted = current_user.received_messages.find(:all, :conditions => ["body LIKE ?", "MAngenommen; #{msg_id}%"])
      return !status_modAccepted.empty?
  end

  def isModRejected?(msg_id)
     status_modAccepted = current_user.received_messages.find(:all, :conditions => ["body LIKE ?", "MAbgelehnt; #{msg_id}%"])
      return !status_modAccepted.empty?
  end
  
  def getModifiedMsg(msg_id)
     status_modified_accepted= current_user.received_messages.find(:all, :conditions => ["body LIKE ?", "MAngenommen; #{msg_id}%"])
     return status_modified_accepted[0]
  end
  
  def getModRejectedMsg(msg_id)
    status_rejected = current_user.received_messages.find(:all, :conditions => ["body LIKE ?", "MAbgelehnt; #{msg_id}%"])
    return status_rejected[0]
  end
  
  def getDiskById(cd_id)
    cd = CompactDisk.find(cd_id)
    return cd
  end
  
  #def isStillThere?(cd_id)  
  #end
  
end

app/views/transaction/history.html.erb
<% content_for :title, "Tausch Historie" %>

<table class="bordered-table zebra-striped">
	<thead>
	<tr>
	    <th>Meine CD(s)</th>
		<th>Eingetauscht gegen</th>
		<th>Tauschpartner</th>
		<th>Datum</th>
	</tr>
	</thead>
	<tbody>
	<% @transactions.each do |t| %>
		<% up = User.find(t.provider_id) %>
		<% ur = User.find(t.receiver_id) %>
		
		<% if t.provider_id == current_user.id %>
			<tr>
			<td>
			<% t.swap_provider.each do |sp| %>
				<% if CompactDisk.exists?(sp.compact_disk_id) %>
					<%= link_to (image_tag getDiskById(sp.compact_disk_id).photo.url(:small)), compact_disk_path(sp.compact_disk_id), :rel=>"popover", :title=>getCD(sp.compact_disk_id).title+" ("+getCD(sp.compact_disk_id).artist+")", :id=>getSongs(getCD(sp.compact_disk_id)) %>
				<% else %>
					CD nicht mehr verfuegbar
				<% end %>
			<% end %>
			</td>
			<td>
			<% t.swap_receiver.each do |sr| %>
				<% if CompactDisk.exists?(sr.compact_disk_id) %>
					<%= link_to (image_tag getDiskById(sr.compact_disk_id).photo.url(:small)), compact_disk_path(sr.compact_disk_id), :rel=>"popover", :title=>getCD(sr.compact_disk_id).title+" ("+getCD(sr.compact_disk_id).artist+")", :id=>getSongs(getCD(sr.compact_disk_id))  %>
				<% else %>
					CD nicht mehr verfuegbar
				<% end %>	
			<% end %>
			</td>
			<td class="middle"><%= link_to ur.firstname + ' ' + ur.lastname, allUserCDs_path(ur) %></td>
			<td class="middle"><%= t.created_at.strftime("%d.%m.%Y (%H:%M Uhr)") %></td>
			</tr>	
		<% else %>
			<tr>
			<td>
			<% t.swap_receiver.each do |sr| %>
				<% if CompactDisk.exists?(sr.compact_disk_id) %>
					<%= link_to (image_tag getDiskById(sr.compact_disk_id).photo.url(:small)), compact_disk_path(sr.compact_disk_id), :rel=>"popover", :title=>getCD(sr.compact_disk_id).title+" ("+getCD(sr.compact_disk_id).artist+")", :id=>getSongs(getCD(sr.compact_disk_id)) %>
				<% else %>
					CD nicht mehr verfuegbar
				<% end %>
			<% end %>
			</td>
			<td>
			<% t.swap_provider.each do |sp| %>
				<% if CompactDisk.exists?(sp.compact_disk_id) %>
					<%= link_to (image_tag getDiskById(sp.compact_disk_id).photo.url(:small)), compact_disk_path(sp.compact_disk_id), :rel=>"popover", :title=>getCD(sp.compact_disk_id).title+" ("+getCD(sp.compact_disk_id).artist+")", :id=>getSongs(getCD(sp.compact_disk_id)) %>
				<% else %>
					CD nicht mehr verfuegbar
				<% end %>
			<% end %>
			</td>
			<td class="middle"><%= link_to up.firstname + ' ' + up.lastname, allUserCDs_path(up) %></td>
			<td class="middle"><%= t.created_at.strftime("%d.%m.%Y (%H:%M Uhr)") %></td>
			</tr>
		<% end %>
	<% end %>
	</tbody>
</table>
<div class="row">
	<div style="padding-left:20px;">
	<%= will_paginate @transactions, :next_label => "Weiter", :previous_label => "Zurück"  %>
	</div>
</div>

app/views/transaction/modifyRequest.html.erb
<% wcd = getWantedCDs(@msg_subject) %>
<% mcd = getMineCDs(@msg_subject) %>
<!--
Tausche 
<% wcd.each do |w| %>
	<%= image_tag getCover(w).photo.url(:small) %>
<% end %>
gegen
<% mcd.each do |m| %>
	<%= image_tag getCover(m).photo.url(:small) %>
<% end %>
<br />

<div id="newReq" class="span4">
	neue Anfrage
</div>
<div id="userCDs" class="span4">
	<% @userCDs.each do |cd| %>
		<%= image_tag cd.photo.url(:small) %>
		<br />
	<% end %>
</div>
-->

<% content_for :title, "Modifizieren" %>

<div class="row grid-move" >
    <div id="myCDs" class="span4 swap box-swap" style="padding:4px;" > 
        <div class="page-header">Meine restlichen CDs </div>
		<% if !@myCDs.empty? %>
			<% @myCDs.each do |cd| %>
				<% if !mcd.include? cd.id.to_s || cd.visible || !cd.in_transaction %>			
						<%= image_tag cd.photo.url(:small), :alt => cd.id, :style => "border: 1px solid white;", :rel=>"popover", :title=>cd.title+" ("+cd.artist+")", :id=>getSongs(cd) %>
				<% end %>
			<% end %>
    	<% else %>
            Sie haben leider keine weiteren CDs
		<% end %>
	</div>
    <div class="span8" style="margin-left:10px;" >
        <div id="wanted" class="wanted box-swap">
            <div class="page-header">Diese CD moechte ich haben </div>
			<%= hidden_field_tag 'msg_id', @msg_id %>
			<% wcd.each do |w| %>
				<%= image_tag getCover(w).photo.url(:small), :alt => w, :style => "border: 1px solid white;", :rel=>"popover", :title=>getCD(w).title+" ("+getCD(w).artist+")", :id=>getSongs(getCD(w)) %>
			<% end %>
		</div>
        <div id="mine" class="mine box-swap">
            <div class="page-header">Diese CDs tausche ich dafuer ein: </div>
			<% mcd.each do |m| %>
				<%= image_tag getCover(m).photo.url(:small), :alt => m, :style => "border: 1px solid white;", :rel=>"popover", :title=>getCD(m).title+" ("+getCD(m).artist+")", :id=>getSongs(getCD(m)) %>
			<% end %>
		</div>
    </div>
    <div id="userCDs" class="span4 swap box-swap" style="margin-left:10px; padding:4px;"  >
		<div class="page-header">Weitere CDs von <%= @user.firstname + " " + @user.lastname %> </div>
		<% @userCDs.each do |cd| %>
			<% if !wcd.include? cd.id.to_s || cd.visible || cd.in_transaction%>
				<%= image_tag cd.photo.url(:small), :alt => cd.id, :style => "border: 1px solid white;", :rel=>"popover", :title=>cd.title+" ("+cd.artist+")", :id=>getSongs(cd) %>
			<% end %>
		<% end %>
	</div>
</div>    

<!--	<div style="margin-top:15px; margin-left:17px;">
        
        <%= link_to "Anfrage senden" , modify_url(@msg_id), :class => "btn large primary disabled" %>
    </div> 
-->
    <div class="row">
		<div class="actions">
			<button class="modifyBt btn">Speichern</button>

			<%= form_tag({:controller => "transaction", :action => "modify"}) do %>
				<%= hidden_field_tag 'cds_mine', ''%>
				<%= hidden_field_tag 'cds_wanted', ''%>
				<%= hidden_field_tag 'user_id', @user.id %>
				<%= hidden_field_tag 'msg_id', @msg_id %>
				<%= submit_tag 'Anfrage senden', :class => "btn primary sendBtn" %>
			<% end %>
		</div>
	</div>
	

app/views/transaction/new.html.erb
<h1>Anfrage gesendet</h1>