config/routes.rb
Projekt::Application.routes.draw do
  devise_for :users
  
  mount Resque::Server, :at => "/resque"
   

  
  
    
    
    match '/search' => 'application#search', :as => :search
  
  match '/autoCompl' => 'application#autoCompl', :as => :autoCompl
  
  scope "(:locale)", :locale => /de|en/ do
    root :to => 'welcome#index', :as => :welcome
    
    resources :user, :except => [:show, :destroy]
    match '/user/most_active' => 'user#most_active', :as => :most_active_user
    match 'user/reset_password' => 'user#reset_password', :as => :reset_password
    match '/user/setAdmin/:id' => 'user#set_as_admin', :as => :set_as_admin, :via => :get
    match '/user/setUser/:id' => 'user#set_as_user', :as => :set_as_user, :via => :get
    match '/user/:id' => 'user#show', :as => :user, :via => :get
    match '/user/:id' => 'user#destroy', :as => :delete_user, :via => :delete
   
    
    resources :devise
    match 'compact_disk/mbrainz/' => 'compact_disk#mbrainz', :as => :mbrainz, :via => :get
    
    resources :compact_disk, :except => [:show, :destroy]
    match '/comapct_disk/delete_demo_songs:id' => 'compact_disk#delete_demo_songs', :as => :delete_demo_songs, :via => :delete
    match '/compact_disk/latest' => 'compact_disk#latest', :as => :latest_cd
    match 'compact_disk/like/:id' => 'compact_disk#like', :as => :like_cd, :via => :get
    match 'comapct_disk/best' => 'compact_disk#best', :as => :best_cd, :via => :get
    match '/compact_disk/:id' => 'compact_disk#show', :as => :compact_disk, :via => :get
    match '/compact_disk/myCDs/:id' => 'compact_disk#myCDs', :as => :myCDs
    match 'compact_disk/swap/:id' => 'compact_disk#swap', :as => :swap_cd
    match '/compact_disk/all_user_cds/:id' => 'compact_disk#all_user_cds', :as => :allUserCDs
    match 'compact_disk/makeVisible/:id' => 'compact_disk#makeVisible', :as => :makeVisible
    match 'compact_disk/:id' => 'compact_disk#destroy', :as => :delete_cd, :via => :delete

    
    match 'transaction/history' => 'transaction#history', :as => :history
    resources :transaction
    match 'transaction/destroy_sent_msg/:id' => 'transaction#destroy_sent_msg', :as => :destroy_sent_msg
    match 'transaction/destroy/:id' => 'transaction#destroy', :as => :destroy
    match 'transaction/rejected/:id' => 'transaction#rejected', :as => :rejected
    match 'transaction/accept/:id' => 'transaction#accept', :as => :accept
    match 'transaction/accepted/:id' => 'transaction#accepted', :as => :accepted
    match 'transaction/modifyAccept/:id' => 'transaction#modifyAccept', :as => :modified_accept
    match 'transaction/modifyAccepted/:id' => 'transaction#modifyAccepted', :as => :modify_accepted
    match 'transaction/modifyReject/:id' => 'transaction#modifyReject', :as => :modified_reject
    match 'transaction/modifyRejected/:id' => 'transaction#modifyRejected', :as => :modified_rejected
    match 'transaction/modify/:id' => 'transaction#modify', :as => :modify, :via => :post
    match 'transaction/modifyRequest/:id' => 'transaction#modifyRequest', :as => :modifyRequest
    
    
    
    match 'impressum' => "application#impressum", :as => :impressum
    match 'admin/manage_users' => 'admin#manage_users', :as => :adminAllUsers
    match 'admin/manage_cds' => 'admin#manage_cds', :as => :adminAllCDs
  end
  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CD - Tauschbörse</title>
  <%= stylesheet_link_tag    "application", "bootstrap" %>
  <%= javascript_include_tag "application","bootstrap-alerts", "bootstrap-buttons", "bootstrap-dropdown", "bootstrap-modal", "bootstrap-twipsy", "bootstrap-popover","bootstrap-scrollspy", "bootstrap-tabs" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<section id="navigation">
		<div class="topbar-wrapper" style="z-index: 5;">
		    <div class="topbar" data-dropdown="dropdown" >
		      <div class="topbar-inner">
		        <div class="container">
		          <%= link_to "SwaRmusik", welcome_path, :class => "brand" %>
		          <ul class="nav">
						<% if !user_signed_in? %>
							<li><a href="<%=new_user_registration_path%>"><%= t('.register')%></a></li>
						<% end %>
		 			<li class="dropdown">
	                    <a class="dropdown-toggle" href="#"><%= t('.categories')%></a>
	                    <ul class="dropdown-menu">
	                        <li><%= link_to t('.cd_all'), compact_disk_index_path %></li>
	                        <li><%= link_to t('.latest_cd'), latest_cd_path %></li>  
							<li><%= link_to t('.most_active_users'), most_active_user_path %></li>
							<li><%= link_to t('.best_cds'), best_cd_path %></li>
	                    </ul>
	                </li>
						<% if !user_signed_in? %>					
					</ul>
						<ul class="nav secondary-nav">			
                            <%= form_for("user", :url => user_session_path, :class => "pull-right") do |f| %>
                                <%= f.text_field :email, :class => "input-small", :placeholder => "Email" %>
                                <%= f.password_field :password, :class => "input-small", :placeholder => "Password" %>			
                                <%= f.submit 'Login'%>
                            <% end %>
						</ul>
                     <% end %>
					<% if user_signed_in? %>
						<li>
							<%= form_tag(search_path, :method => "get") do %>
						  	<%= text_field_tag :querry, nil, :placeholder => t('.search_text')%>
							<% end %>
						</li>
		          	</ul>
					<% end %>
					<% if user_signed_in? %>
		          	<ul class="nav secondary-nav">
					<% if current_user.role_id == User.admin %>
						<li class="dropdown">
							<a class="dropdown-toggle" href="#">Admin</a>
							<ul class="dropdown-menu">
								<li><%= link_to t('.manage_users'), adminAllUsers_path %></li>
								<li><%= link_to t('.manage_cds'), adminAllCDs_path %></li>
							</ul>
						</li>
					<% end %>			
		            <li class="dropdown">
									<% if getUnreadMessageCount(current_user.id) > 0 %>
		             		<a href="#" class="dropdown-toggle"><%= current_user.firstname+" "+current_user.lastname+" ("+getUnreadMessageCount(current_user.id).to_s+")" %></a>
									<% else %>
										<a href="#" class="dropdown-toggle"><%= current_user.firstname+" "+current_user.lastname %></a>
									<% end %>
		              <ul class="dropdown-menu">
		                <li>
                        <%= link_to t('.user_cd_index'), myCDs_url(current_user.id) %>
                    </li>
                    <li>
												<% if getUnreadMessageCount(current_user.id) > 0 %>
                        	<%= link_to t('.transactions')+ " (" + getUnreadMessageCount(current_user.id).to_s + ")", transaction_index_path %>
												<% else %>
													<%= link_to t('.transactions'), transaction_index_path %>
												<% end %>
                    </li>
										<li class="divider"></li>
										<li>
                        <%= link_to t('.user_show'), user_path(current_user.id) %>
                    </li>
		                
										<li>
											<%= link_to(t('.logout'), destroy_user_session_path) %>
										</li>
		              </ul>
		            </li>
		          </ul>
							<% end %>
		        </div>
		      </div><!-- /topbar-inner -->
		    </div><!-- /topbar -->
		  </div><!-- /topbar-wrapper -->
	</section>
        
        <div class="container">
			<div class="content">
            	<div class="page-header">
<!--                <div class="row show-grid"> -->
<!--                    <div class="span8"> -->
                        <h2> 
							<%= yield(:title) %>  
						
						</h2>
<!--                    </div> -->                    
<!--				</div>	-->
            	</div>
			
				<div class="row">
<!--            	<div class="content">-->
                	<%= yield %> 
            	</div>
			</div>
            
			<footer>
                &copy; RailsProjekt 2011 <%= link_to  "Impressum", impressum_path %>	
            </footer>
        </div>
				</div>
				
</body>
</html>